language: node_js
node_js:
  - "10.9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - cd FightTimeLine
  - cd ClientApp
  - npm install -g @angular/cli
script:
- npm install
- ng build --prod