language: node_js
node_js:
  - "10.9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - cd FightTimeLine
  - cd ClientApp
  - npm install -g @angular/cli
script:
- npm install
- node --max_old_space_size=8192 "node_modules/@angular/cli/bin/ng" build --configuration=production